
development:
  adapter: postgresql
  encoding: unicode
  database: whiskey_dev
  pool: 5
  username: mashype
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: whiskey_test
  pool: 5
  username: mashype
  password:

production:
  database: <%= ENV["DATABASE_NAME"] %>
  username: wakdmoeihcemgr
  password: <%= ENV["DATABASE_PASSWORD"] %>
  adapter: postgresql
  host: ec2-23-21-121-220.compute-1.amazonaws.com

